-- This file is generated by SWIG. Please do *not* modify by
--hand.
--
with eGL.Pointers;
with Interfaces.C.Pointers;
with Interfaces.C.Strings;
with System;
package eGL.NativeDisplayType is

   -- Item
   --
   subtype Item is eGL.Pointers.Display_Pointer;

   type Item_array is
     array (Interfaces.C.size_t range <>)
            of aliased eGL.NativeDisplayType.Item;

   -- Pointers.Pointer
   --

   -- Pointer
   --
   type Pointer is access all eGL.NativeDisplayType.Item;

   type Pointer_array is
     array (Interfaces.C.size_t range <>)
            of aliased eGL.NativeDisplayType.Pointer;

   -- pointer_Pointers.Pointer
   --

   -- pointer_Pointer
   --
   type pointer_Pointer is access all eGL.NativeDisplayType.Pointer;

end eGL.NativeDisplayType;
