-- This file is generated by SWIG. Please do *not*
--modify by hand.
--
with eGL.Pointers;
with Interfaces.C.Pointers;
with Interfaces.C.Strings;
with System;
package eGL.pointer_Pointers is

   -- Display_Pointer_Pointers.Pointer
   --

   -- Display_Pointer_Pointer
   --
   type Display_Pointer_Pointer is access all eGL.Pointers.Display_Pointer;

   -- NativeWindowType_Pointer_Pointers.Pointer
   --

   -- NativeWindowType_Pointer_Pointer
   --
   type NativeWindowType_Pointer_Pointer is access all
     eGL.Pointers.NativeWindowType_Pointer;

   -- NativePixmapType_Pointer_Pointers.Pointer
   --

   -- NativePixmapType_Pointer_Pointer
   --
   type NativePixmapType_Pointer_Pointer is access all
     eGL.Pointers.NativePixmapType_Pointer;

   -- EGLint_Pointer_Pointers.Pointer
   --

   -- EGLint_Pointer_Pointer
   --
   type EGLint_Pointer_Pointer is access all eGL.Pointers.EGLint_Pointer;

   -- EGLBoolean_Pointer_Pointers.Pointer
   --

   -- EGLBoolean_Pointer_Pointer
   --
   type EGLBoolean_Pointer_Pointer is access all
     eGL.Pointers.EGLBoolean_Pointer;

   -- EGLenum_Pointer_Pointers.Pointer
   --

   -- EGLenum_Pointer_Pointer
   --
   type EGLenum_Pointer_Pointer is access all eGL.Pointers.EGLenum_Pointer;

   -- EGLConfig_Pointer_Pointers.Pointer
   --

   -- EGLConfig_Pointer_Pointer
   --
   type EGLConfig_Pointer_Pointer is access all eGL.Pointers.EGLConfig_Pointer;

   -- EGLContext_Pointer_Pointers.Pointer
   --

   -- EGLContext_Pointer_Pointer
   --
   type EGLContext_Pointer_Pointer is access all
     eGL.Pointers.EGLContext_Pointer;

   -- EGLDisplay_Pointer_Pointers.Pointer
   --

   -- EGLDisplay_Pointer_Pointer
   --
   type EGLDisplay_Pointer_Pointer is access all
     eGL.Pointers.EGLDisplay_Pointer;

   -- EGLSurface_Pointer_Pointers.Pointer
   --

   -- EGLSurface_Pointer_Pointer
   --
   type EGLSurface_Pointer_Pointer is access all
     eGL.Pointers.EGLSurface_Pointer;

   -- EGLClientBuffer_Pointer_Pointers.Pointer
   --

   -- EGLClientBuffer_Pointer_Pointer
   --
   type EGLClientBuffer_Pointer_Pointer is access all
     eGL.Pointers.EGLClientBuffer_Pointer;

end eGL.pointer_Pointers;
